# Generated by Django 6.0.3 on 2026-06-16 15:30

import core.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number1', models.CharField()),
                ('phone_number2', models.CharField(blank=True, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('membership', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=core.models.logo_path)),
                ('sale_target', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('top_ten_filter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes')),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_name1')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to='core.customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpanseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_name3')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, default='will_be_auto_generated', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='Inventory_Photo/no_photo.png', null=True, upload_to=core.models.inventory_photo_path)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('Other', 'Other')])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('barcode_number', models.CharField(blank=True, max_length=13, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to=core.models.barcode_path)),
                ('reorder_alert', models.IntegerField(default=5)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('Out', 'Out'), ('In', 'In')], default='Out')),
                ('type', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Adjustment', 'Adjustment')], default='Sale')),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment', to='core.inventory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total times this code can be used.', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, help_text='Times a single user can use this code.', null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_name4')],
            },
        ),
        migrations.CreateModel(
            name='Purcase',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Pending Delete', 'Pending Delete'), ('Deleted', 'Deleted')], default='Paid')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cash On Delivery', 'Cash On Delivery')], max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.promotioncode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
            options={
                'ordering': ['invoice_number'],
                'get_latest_by': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventory')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_purchase', to='core.purcase')),
            ],
            options={
                'ordering': ['purchase'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cash On Delivery', 'Cash On Delivery')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Pending Delete', 'Pending Delete'), ('Deleted', 'Deleted')], default='Paid')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sale', to='core.customer')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.promotioncode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
            options={
                'ordering': ['invoice_number'],
                'get_latest_by': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='core.promotioncode')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_sale', to='core.sale')),
            ],
            options={
                'ordering': ['sale'],
            },
        ),
        migrations.CreateModel(
            name='ExpanseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to=core.models.referemce_photo_path)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Deleted', 'Deleted')], default='Paid')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expanse_category', to='core.expansecategory')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number1', models.CharField()),
                ('phone_number2', models.CharField(blank=True, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('membership', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purcase',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_purchase', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to='core.supplier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_case_insensitive_name2')],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='core.unit'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_message', models.CharField(blank=True, max_length=100, null=True)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=core.models.user_profile_path)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femal', 'Femal')])),
                ('date_of_brith', models.DateField(blank=True, null=True)),
                ('membership', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
