# Generated by Django 6.0.3 on 2026-08-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 20, 14, 46, 26, 385689, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 20, 14, 46, 26, 380735, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 20, 14, 46, 26, 386674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 20, 14, 46, 26, 390726, tzinfo=datetime.timezone.utc)),
        ),
    ]
