# Generated by Django 6.0.3 on 2026-06-20 16:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_store_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='short_message',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 20, 16, 35, 54, 547008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned')], default='Active'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='store', to='core.store'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
