# Generated by Django 6.0.3 on 2026-06-23 17:11

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_store_is_selected_alter_userprofile_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 17, 11, 13, 26282, tzinfo=datetime.timezone.utc)),
        ),
    ]
