# Generated by Django 6.0.3 on 2026-06-23 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inventoryadjustment_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 17, 43, 0, 474560, tzinfo=datetime.timezone.utc)),
        ),
    ]
