# Generated by Django 6.0.3 on 2026-06-24 04:53

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sale_store_alter_userprofile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='expanseitem',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='purcase',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 4, 53, 35, 671795, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(default=core.models.store_selecte_default, on_delete=django.db.models.deletion.PROTECT, related_name='store', to='core.store'),
        ),
    ]
