# Generated by Django 6.0.3 on 2026-06-24 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_promotioncode_store_alter_customer_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 6, 2, 57, 795543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 6, 2, 57, 802975, tzinfo=datetime.timezone.utc)),
        ),
    ]
