# Generated by Django 6.0.3 on 2026-06-24 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_store_created_on_alter_userprofile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 6, 46, 24, 917502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 6, 46, 24, 925395, tzinfo=datetime.timezone.utc)),
        ),
    ]
