# Generated by Django 6.0.3 on 2026-06-24 07:06

import datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_store_created_on_alter_store_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 7, 6, 25, 111700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 7, 6, 25, 119449, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('code'), name='unique_case_insensitive_name5'),
        ),
    ]
