# Generated by Django 6.0.3 on 2026-06-24 16:51

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_store_code_alter_store_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='expanseitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='purcase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 16, 51, 26, 701731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.logo_path),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 16, 51, 26, 709794, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store', to='core.store'),
        ),
    ]
