# Generated by Django 6.0.3 on 2026-06-24 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customer_store_alter_expanseitem_store_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotioncode',
            name='unique_case_insensitive_name4',
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 17, 7, 28, 256402, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 17, 7, 28, 264151, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='promotioncode',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique_room_per_floor'),
        ),
    ]
