# Generated by Django 6.0.3 on 2026-06-24 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_promotioncode_unique_case_insensitive_name4_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promotioncode',
            name='unique_room_per_floor',
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 17, 32, 9, 617222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 17, 32, 9, 625309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='promotioncode',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique_code_store'),
        ),
    ]
