# Generated by Django 6.0.3 on 2026-06-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_promotioncode_unique_room_per_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 25, 4, 59, 58, 464895, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 25, 4, 59, 58, 472548, tzinfo=datetime.timezone.utc)),
        ),
    ]
