# Generated by Django 6.0.3 on 2026-06-25 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_promotioncode_name_alter_store_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 25, 5, 7, 26, 223641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 25, 5, 7, 26, 231455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='unique_code_store_inventory'),
        ),
    ]
