# Generated by Django 6.0.3 on 2026-07-06 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_store_created_on_alter_userprofile_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 6, 14, 35, 55, 106697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number1',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 6, 14, 35, 55, 104060, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number1',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 6, 14, 35, 55, 111681, tzinfo=datetime.timezone.utc)),
        ),
    ]
