# Generated by Django 6.0.3 on 2026-07-16 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customer_created_on_alter_store_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_attempts',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_change_date',
            field=models.DateField(default=datetime.datetime(2026, 7, 16, 15, 51, 28, 874452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 15, 51, 28, 869240, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 15, 51, 28, 866522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 15, 51, 28, 874391, tzinfo=datetime.timezone.utc)),
        ),
    ]
