# Generated by Django 6.0.3 on 2026-07-16 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprofile_number_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 16, 8, 34, 532656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 16, 8, 34, 530010, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 16, 16, 8, 34, 537719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_change_date',
            field=models.DateField(),
        ),
    ]
