# Generated by Django 6.0.3 on 2026-08-19 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customer_created_on_alter_store_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 19, 3, 20, 27, 643774, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 19, 3, 20, 27, 639057, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 19, 3, 20, 27, 644731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 19, 3, 20, 27, 648711, tzinfo=datetime.timezone.utc)),
        ),
    ]
